[package]
name = "find9"
version = "0.1.0"
edition = "2021"

[dependencies]
#rlibdns = "0.1.1"
#rlibdns = "https://github.com/ethernaught/rlibdns" }
rlibdns = { path = "../rlibdns" }
rlibbencode = { git = "https://github.com/sectorrent/rlibbencode" }
